export const dynamic = "force-dynamic";
export const metadata = {
  title: {
    default: "Privacy Policy",
    card: "summary_large_image",
  },
};

const PrivacyPolicyPage = () => {
  return (
    <div className="container mx-auto px-6 py-12 ">
      <h1 className="text-3xl font-semibold text-center text-seo-first-color mb-6">
        Privacy Policy
      </h1>
      <p className="text-sm text-seo-third-color text-center mb-8">
        Last updated: April 21, 2025
      </p>

      <p className="text-base text-seo-second-color mb-6">
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="text-base text-seo-second-color mb-6">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold text-seo-second-color mt-8 mb-4">
        Interpretation and Definitions
      </h2>

      <h3 className="text-xl font-semibold text-seo-forth-color mb-2">
        Interpretation
      </h3>
      <p className="text-base text-seo-second-color mb-6">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className="text-xl font-semibold text-seo-forth-color mb-2">
        Definitions
      </h3>
      <p className="text-base text-seo-second-color mb-6">
        For the purposes of this Privacy Policy:
      </p>

      <ul className="list-disc pl-6 text-base text-seo-second-color mb-6">
        <li>
          <strong>Account:</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate:</strong> means an entity that controls, is
          controlled by or is under common control with a party, where
          &quot;control&quot; means ownership of 50% or more of the shares,
          equity interest, or other securities entitled to vote for election of
          directors or other managing authority.
        </li>
        <li>
          <strong>Company:</strong> refers to Free Digital Tool.
        </li>
        <li>
          <strong>Cookies:</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website.
        </li>
        <li>
          <strong>Country:</strong> refers to: Bangladesh
        </li>
        <li>
          <strong>Device:</strong> means any device that can access the Service
          such as a computer, a cellphone, or a digital tablet.
        </li>
        <li>
          <strong>Personal Data:</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service:</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider:</strong> means any natural or legal person
          who processes the data on behalf of the Company.
        </li>
        <li>
          <strong>Third-party Social Media Service:</strong> refers to any
          website or social network website through which a User can log in or
          create an account to use the Service.
        </li>
        <li>
          <strong>Usage Data:</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website:</strong> refers to Free Digital Tool, accessible from{" "}
          <a
            href="https://freedigitaltool.com"
            className="text-seo-first-color hover:underline"
          >
            freedigitaltool.com
          </a>
        </li>
        <li>
          <strong>You:</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold text-seo-second-color mt-8 mb-4">
        Collecting and Using Your Personal Data
      </h2>

      <h3 className="text-xl font-semibold text-seo-forth-color mb-2">
        Types of Data Collected
      </h3>
      <h4 className="text-lg font-semibold text-seo-forth-color mb-2">
        Personal Data
      </h4>
      <p className="text-base text-seo-second-color mb-6">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className="list-disc pl-6 text-base text-seo-second-color mb-6">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="text-lg font-semibold text-seo-forth-color mb-2">
        Usage Data
      </h4>
      <p className="text-base text-seo-second-color mb-6">
        Usage Data is collected automatically when using the Service.
      </p>
      <p className="text-base text-seo-second-color mb-6">
        Usage Data may include information such as Your Device&apos;s Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers, and other
        diagnostic data.
      </p>

      <h4 className="text-lg font-semibold text-seo-forth-color mb-2">
        Information from Third-Party Social Media Services
      </h4>
      <p className="text-base text-seo-second-color mb-6">
        The Company allows You to create an account and log in to use the
        Service through the following Third-party Social Media Services:
      </p>
      <ul className="list-disc pl-6 text-base text-seo-second-color mb-6">
        <li>Google</li>
        <li>Facebook</li>
        <li>Instagram</li>
        <li>Twitter</li>
        <li>LinkedIn</li>
      </ul>
      <p className="text-base text-seo-second-color mb-6">
        If You decide to register through or otherwise grant us access to a
        Third-Party Social Media Service, We may collect Personal data that is
        already associated with Your Third-Party Social Media Service&apos;s
        account, such as Your name, Your email address, Your activities, or Your
        contact list associated with that account.
      </p>

      <h4 className="text-lg font-semibold text-seo-forth-color mb-2">
        Tracking Technologies and Cookies
      </h4>
      <p className="text-base text-seo-second-color mb-6">
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service. The technologies We use may include:
      </p>
      <ul className="list-disc pl-6 text-base text-seo-second-color mb-6">
        <li>
          <strong>Cookies or Browser Cookies.</strong> A cookie is a small file
          placed on Your Device.
        </li>
        <li>
          <strong>Web Beacons.</strong> Certain sections of our Service and our
          emails may contain small electronic files known as web beacons.
        </li>
      </ul>

      <p className="text-base text-seo-second-color mb-6">
        Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies.
        Persistent Cookies remain on Your personal computer or mobile device
        when You go offline, while Session Cookies are deleted as soon as You
        close Your web browser.
      </p>

      <h3 className="text-xl font-semibold text-seo-forth-color mb-4">
        Use of Your Personal Data
      </h3>
      <ul className="list-disc pl-6 text-base text-seo-second-color mb-6">
        <li>
          <strong>To provide and maintain our Service</strong>, including to
          monitor the usage of our Service.
        </li>
        <li>
          <strong>To manage Your Account:</strong> to manage Your registration
          as a user of the Service.
        </li>
        <li>
          <strong>For the performance of a contract:</strong> development,
          compliance and undertaking of contracts.
        </li>
        <li>
          <strong>To contact You:</strong> by email, SMS, or mobile
          notifications.
        </li>
        <li>
          <strong>For business transfers:</strong> to evaluate or conduct a
          merger, sale of assets, or other transfers.
        </li>
        <li>
          <strong>For other purposes:</strong> to improve our service and user
          experience.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold text-seo-second-color mt-8 mb-4">
        Contact Us
      </h2>
      <p className="text-base text-seo-second-color mb-6">
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="list-disc pl-6 text-base text-seo-second-color mb-6">
        <li>
          By email:{" "}
          <a
            href="mailto:admin@freedigitaltool.com"
            className="text-seo-first-color hover:underline"
          >
            admin@freedigitaltool.com
          </a>
        </li>
      </ul>
    </div>
  );
};

export default PrivacyPolicyPage;
